### ISSUE TITLE
file_get_contents errors are ugly

### ISSUE THREAD

**Issue by billcreswell** [pluck-cms/pluck_gravatar#2]
Theoretically, file_get_contents is supposed to return false, but I get warnings.

**Comment by ekyo-pl** [comment]
Why this issue is inside pluck_gravatar and not inside pluck?

Could you past more details?

**Comment by billcreswell** [comment]
It is only an issue with this plugin, and I think I was having trouble catching errors when the function failed. Since it was working for me, I hadn't thought about it for a while.

**Comment by ekyo-pl** [comment]
Header problem? Its serwer problem. Head is HTTP/1.1 and file_get_contents use 1.0 only. So it can be fixed only on server.

I put @ sign before file_get_contents. It will not show warning.
